const greetingTranslation = [
    {      
    lang: 'en',
    morning: 'Good morning',
    afternoon: 'Good afternoon',
    evening: 'Good evening',
    night: 'Good night',
    settings: 'Settings',
    pleylist: 'pleylist',
    player: 'Player',
    weather: 'Weather',
    time: 'Time',
    date: 'Date',
    greeting: 'Greeting',
    quote: 'Quote',
    collections: 'Background images',
    github: 'GitHub ',
    tags: 'Tag for ',
    links: 'Links',
    addLinks: '+ New Link',
    back: 'Back',
    linksName: 'NAME',
    inputLink: 'LINKS',
    create: 'Create'
    },   
    {      
    lang: 'ru',
    morning: 'Доброе утро',
    afternoon: 'Добрый день',
    evening: 'Добрый вечер',
    night: 'Спокойной ночи',
    settings: 'Настройки',
    pleylist: 'Плейлист',
    player: 'Плейер',
    weather: 'Погода',
    time: 'Время',
    date: 'Дата',
    greeting: 'Приветствие',
    quote: 'Цитаты',
    collections: 'Фоновое изображение',
    github: 'Гит Хаб ',
    tags: 'Тег для ',
    links: 'Ссылки',
    addLinks: 'Добавить ссылку',
    back: 'Назад',
    linksName: 'НАЗВАНИЕ',
    inputLink: 'Адрес',
    create: 'Создать'
    }  
  ]
  export default greetingTranslation;